version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_unique_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

      - name: state
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["SP", "GO", "RJ", "MA", "PB", "CE", "MT", "RO", "TO", "RR","PR", "RS", "ES", "PE", "AM", "SE", "BA", "AP", "AL", "PA","RN", "PI", "AC", "DF", "SC", "MG", "MS"]

  
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_unique_id

      - name: order_status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['created','approved','invoiced','shipped','delivered','canceled','unavailable','processing']

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id

      - name: product_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id

      - name: seller_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_sellers')
                field: seller_id

      - name: price
        tests:
          - not_null

  - name: stg_order_payments
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id

      - name: payment_value
        tests:
          - not_null

  - name: stg_order_reviews
    columns:
      - name: review_id
        tests:
          - not_null

      - name: review_score
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: stg_sellers
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique

  - name: stg_geolocation
    columns:
      - name: zip_code_prefix
        tests:
          - not_null

