USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

CREATE DATABASE IF NOT EXISTS OLIST_DB;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.RAW;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.FILEFORMAT;

CREATE DATABASE DBT_DATABASE;

CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='OLIST_DB.RAW'
  COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

-- Step 6: Grant permissions to the `transform` role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

GRANT ALL ON DATABASE OLIST_DB TO ROLE TRANSFORM;

GRANT ALL ON ALL SCHEMAS IN DATABASE OLIST_DB TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE OLIST_DB TO ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA OLIST_DB.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA OLIST_DB.RAW TO ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA OLIST_DB.STAGING TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA OLIST_DB.STAGING TO ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA OLIST_DB.FILEFORMAT TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA OLIST_DB.FILEFORMAT TO ROLE TRANSFORM;

GRANT ALL ON DATABASE DBT_DATABASE TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DBT_DATABASE TO ROLE TRANSFORM;

